### ISSUE TITLE
Can you please post benchmarks results?

### ISSUE THREAD

**Issue by shujaatak** [fallenwood/simple-http-benchmarks#1]
It would be highly appreciated if you please post the results in the readme or somewhere.

**Comment by fallenwood** [comment]
Hi @shujaatak, the results can be found inside archive (e.g. https://raw.githubusercontent.com/fallenwood/simple-http-benchmarks/dev/archive/20240307.md), it's the repo initially for self-notes, so there is no fancy format now

**Comment by shujaatak** [comment]
Thank you! Axum, dotnet-aot, and gin are impressive. I was expecting to see pingora benchmarks but it's missing.

**Comment by fallenwood** [comment]
@shujaatak  pingora is not a web server in the benchmark game, it's under proxy folder https://github.com/fallenwood/simple-http-benchmarks/blob/dev/proxy/20240301.md and  https://github.com/fallenwood/simple-http-benchmarks/blob/dev/proxy/20240302.md
